# Generated by Django 6.0 on 2025-12-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Одноместный'), ('double', 'Двухместный'), ('triple', 'Четырехместный')], max_length=10, verbose_name='Тип номера'),
        ),
    ]
